name: auto commit

on:
  workflow_dispatch:
  schedule:
    - cron: '18 11 * * 6'

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: echo
        shell: bash
        run: |
          echo $(date) > date
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'date'
          message: ':clown_face: update date'
