name: build docker image

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - '.env'
      - 'Pipfile'
      - 'Pipfile.lock'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: eat-pray-ai/blackheart2/.github/actions/github-packages@main
