name: blackheart2

on:
  workflow_dispatch:
  schedule:
    - cron: '52 0 * * *'
    - cron: '18 3 * * *'
    - cron: '19 10 * * *'
    - cron: '55 15 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eat-pray-ai/blackheart2:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - id: generate
        shell: bash
        env:
          YOUTUBE_PLAYLISTS: ${{ vars.YOUTUBE_PLAYLISTS }}
        run: |
          cd /blackheart2
          ./entrypoint.sh
      - name: upload video
        uses: eat-pray-ai/yutu/actions/upload@main
        with:
          credential: ${{ secrets.YOUTUBE_CREDENTIAL }}
          token: ${{ secrets.YOUTUBE_TOKEN }}
          file: "./${{ steps.generate.outputs.title }}.mp4"
          title: ${{ steps.generate.outputs.title }}
          description: ${{ steps.generate.outputs.description }}
          tags: ${{ steps.generate.outputs.tag }}
          rest-flags: "-y ${{ steps.generate.outputs.playlistId }} -p public -k true -g 22"
      - shell: bash
        run: |
          cat ./youtube.token.json | base64 > ./youtube.token.b64
          gpg --batch -c --cipher-algo AES256 --passphrase ${{ secrets.GPG_PASSPHRASE }} ./youtube.token.b64
          ls -alh
      - name: cache token
        uses: actions/cache@v4
        with:
          path: ./youtube.token.b64.gpg
          key: youtube-token-${{ hashFiles('./youtube.token.b64.gpg') }}
