name: blackheart2

on:
  workflow_dispatch:
  schedule:
    - cron: '52 0 * * *'
    - cron: '18 3 * * *'
    - cron: '19 10 * * *'
    - cron: '55 15 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eat-pray-ai/blackheart2:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: generate
        shell: bash
        env:
          YOUTUBE_PLAYLISTS: ${{ vars.YOUTUBE_PLAYLISTS }}
        run: |
          mv ./* /blackheart2
          cd /blackheart2
          pipenv run python ./main.py
      - name: upload video
        uses: eat-pray-ai/yutu/actions/upload@main
        with:
          credential: ${{ secrets.YOUTUBE_CREDENTIAL }}
          token: ${{ secrets.YOUTUBE_TOKEN }}
          file: "./${{ steps.generate.outputs.title }}.mp4"
          title: ${{ steps.generate.outputs.title }}
          description: ${{ steps.generate.outputs.description }}
          tags: ${{ steps.generate.outputs.tag }}
          rest-flags: "-y ${{ steps.generate.outputs.playlistId }} -p public -k true -g 22"
      - name: update token
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.ENCRYPT_PAT }}
        run: |
          cp ./youtube.token.json /blackheart2
          cd /blackheart2
          pipenv run python ./encrypt.py
