name: blackheart2

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eat-pray-ai/blackheart2:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - id: generate
        shell: bash
        run: |
          cd /blackheart2
          ./entrypoint.sh
      - name: upload video
        uses: eat-pray-ai/yutu/actions/upload@main
        with:
          credential: ${{ secrets.YOUTUBE_CREDENTIAL }}
          token: ${{ secrets.YOUTUBE_TOKEN }}
          flags: "-f ./${{ steps.generate.outputs.title }}.mp4 -t ${{ steps.generate.outputs.title }} -T ${{ steps.generate.outputs.tag }} -p public -k true -g 22"
