name: blackheart2

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: generate
        uses: eat-pray-ai/blackheart2/.github/actions/generate-video@main
      - id: title
        run: echo "title=$(basename ${{ steps.generate.outputs.file}} | cut -d'.' -f1)" >> $GITHUB_OUTPUT
      - name: upload video
        uses: eat-pray-ai/yutu/actions/upload@main
        with:
          token: ${{ secrets.YOUTUBE_TOKEN }}
          flags: "-f ${{ steps.generate.outputs.file}} -t ${{ steps.title.outputs.title}} -p public -g 22"
