name: blackheart2

on:
  workflow_dispatch:
  schedule:
    - cron: '52 0 * * *'
    - cron: '18 3 * * *'
    - cron: '19 10 * * *'
    - cron: '55 15 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eat-pray-ai/blackheart2:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - id: generate
        shell: bash
        run: |
          cd /blackheart2
          ./entrypoint.sh
      - name: upload video
        uses: eat-pray-ai/yutu/actions/upload@main
        with:
          credential: ${{ secrets.YOUTUBE_CREDENTIAL }}
          token: ${{ secrets.YOUTUBE_TOKEN }}
          file: "./${{ steps.generate.outputs.title }}.mp4"
          title: ${{ steps.generate.outputs.title }}
          description: ${{ steps.generate.outputs.description }}
          tags: ${{ steps.generate.outputs.tag }}
          rest-flags: "-p public -k true -g 22"
