name: blackheart2

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: generate
        uses: eat-pray-ai/blackheart2/.github/actions/generate-video@main
      - name: upload video
        uses: eat-pray-ai/yutu/actions/upload@main
        with:
          credential: ${{ secrets.YOUTUBE_CREDENTIAL }}
          token: ${{ secrets.YOUTUBE_TOKEN }}
          flags: "-f ${{ github.workspace }}/${{ steps.generate.outputs.title }}.mp4 -t ${{ steps.generate.outputs.title }} -p public -k true -g 22"
